#ifndef VISUAL_CONFIG_H
#define VISUAL_CONFIG_H
// Copyright (c) 2000, 2001, 2002, 2003 by David Scherrer and others.
// See the file liscence.txt for complete liscence terms.
// See the file authors.txt for a complete list of contributors.
/*
 * Configuration header file.  This file is automatically generated by configure.
 * You should change config.h.in and configure.ac rather than this file
 * See also platform.h
 */

/*
 * Set this to 1 if we are building on some Win32 platform
 */
#undef HAVE_WIN32_API

/*
 * Set this to 1 if your platform supports GtkGLarea.
 */
#undef HAVE_GTK_GL_AREA

/*
 * Set this to 1 if your platform supports GtkGLExtmm.
 * This support is experimental
 */
#define HAVE_GTK_GL_EXT_MM

/*
 * Set this to 1 if you want to build Visual with support for Numeric
 */
#define VISUAL_HAVE_NUMERIC 1

/*
 * Set this to 1 if you want to build Visual with support for Numarray
 */
#define VISUAL_HAVE_NUMARRAY 1

#endif // !VISUAL_CONFIG_H
